services:
  db:
    image: postgres:16.5
    container_name: canteen_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG:-latest}
    container_name: canteen_web
    restart: unless-stopped
    command:
      - /scripts/start-django-prod.sh
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - private
      - public
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  caddy:
    image: ghcr.io/${GITHUB_REPOSITORY}-caddy:${IMAGE_TAG:-latest}
    container_name: canteen_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./deployment/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/srv/static:ro
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - private
      - public

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - private
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:
  caddy_data:
  caddy_config:

networks:
  public:
  private:
    internal: true
